info:
  contact: {}
  license: {}
paths:
  /:
    get:
      description: A sample af a GET request
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - API
  /post/:
    post:
      description: A test API request
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - API
  /swagger.json:
    get:
      description: Swagger JSON data for the JS Swagger renderer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - swagger
swagger: "2.0"
